Added debug code

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -77,6 +77,57 @@ jobs:
       - when:
           condition: <<parameters.dev>>
           steps:
+            # debug
+            - run:
+                name: Install AWS CLI
+                command: |
+                  export PIP=$(which pip pip3 | head -1)
+                  if [[ -n $PIP ]]; then
+                    if which sudo > /dev/null; then
+                      sudo $PIP install awscli --upgrade
+                    else
+                      # This installs the AWS CLI to ~/.local/bin. Make sure that ~/.local/bin is in your $PATH.
+                      $PIP install awscli --upgrade --user
+                    fi
+                  elif [[ $(which unzip curl | wc -l) -eq 2 ]]; then
+                    cd
+                    curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
+                    unzip awscli-bundle.zip
+                    if which sudo > /dev/null; then
+                      sudo ~/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
+                    else
+                      # This installs the AWS CLI to the default location (~/.local/lib/aws) and create a symbolic link (symlink) at ~/bin/aws. Make sure that ~/bin is in your $PATH.
+                      awscli-bundle/install -b ~/bin/aws
+                    fi
+                    rm -rf awscli-bundle*
+                    cd -
+                  else
+                    echo "Unable to install AWS CLI. Please install pip."
+                    exit 1
+                  fi
+            - run:
+                name: Configure AWS Access Key ID
+                command: |
+                  aws configure set aws_access_key_id \
+                  $DEV_AWS_ACCESS_KEY_ID \
+                  --profile default
+            - run:
+                name: Configure AWS Secret Access Key
+                command: |
+                  aws configure set aws_secret_access_key \
+                  $DEV_AWS_SECRET_ACCESS_KEY \
+                  --profile default
+            - run:
+                name: Configure AWS default region
+                command: |
+                  aws configure set region $AWS_REGION \
+                  --profile default
+            - run:
+                name: Debugging
+                command: |
+                  aws s3 ls s3://ridi-select-dev
+                  aws s3 ls s3://ridi-library-dev
+            # debug
             - aws-s3/sync:
                 from: out
                 to: ${S3_BUCKET_DEV}
